function [] = Display_Molecule( mol, atoms)
%Display the molecule in the space
%   mol: the GAUSSIAN result
%   atoms: is the vector containing the numberof atoms to be shown

%figure, hold on, grid on
hold on, grid on
%model: copy and paste to consider other elements
% scatter3(X,Y,Z,... 
%             DIMENSION,... 
%             'Filled','MarkerEdgeColor','k',...
%             'MarkerFaceColor',[COLOR-RGB]...
%         )

try 
    atomsList = atoms;
catch
    atomsList = 1:mol.n_atoms;
end

for i = atomsList

    if strcmp(mol.element(i),'H') %Hydrogen
        scatter3(mol.x(i),mol.y(i),mol.z(i),... 
            80,... 
            'Filled','MarkerEdgeColor','k',...
            'MarkerFaceColor',[.9 .9 .9]...
        )
    elseif strcmp(mol.element(i),'C') %Carbon
        scatter3(mol.x(i),mol.y(i),mol.z(i),... 
            100,... 
            'Filled','MarkerEdgeColor','k',...
            'MarkerFaceColor',[.3 .3 .3]...
        )
    elseif strcmp(mol.element(i),'Cl') %Carbon
        scatter3(mol.x(i),mol.y(i),mol.z(i),... 
            100,... 
            'Filled','MarkerEdgeColor','k',...
            'MarkerFaceColor',[0 1 0]...
        )
    elseif strcmp(mol.element(i),'S') %Sulfur
        scatter3(mol.x(i),mol.y(i),mol.z(i),... 
            180,... 
            'Filled','MarkerEdgeColor','k',...
            'MarkerFaceColor',[1 .8 .4]...
        )
    elseif strcmp(mol.element(i),'N') %Nytrogen
        scatter3(mol.x(i),mol.y(i),mol.z(i),... 
            180,... 
            'Filled','MarkerEdgeColor','k',...
            'MarkerFaceColor',[0 0 1]...
        )
    elseif strcmp(mol.element(i),'Fe') || strcmp(mol.element(i),'FE') %Iron
        scatter3(mol.x(i),mol.y(i),mol.z(i),... 
            200,... 
            'Filled','MarkerEdgeColor','k',...
            'MarkerFaceColor',[1 0.5 0.2]...
        )
    elseif strcmp(mol.element(i),'O') %Iron
        scatter3(mol.x(i),mol.y(i),mol.z(i),... 
            200,... 
            'Filled','MarkerEdgeColor','k',...
            'MarkerFaceColor',[1 0 0]...
        )
    elseif strcmp(mol.element(i),'B') %Boron
        scatter3(mol.x(i),mol.y(i),mol.z(i),... 
            200,... 
            'Filled','MarkerEdgeColor','k',...
            'MarkerFaceColor',[0.9 0.4 0.9]...
        )
    elseif strcmp(mol.element(i),'F') %Fluorine
        scatter3(mol.x(i),mol.y(i),mol.z(i),... 
            200,... 
            'Filled','MarkerEdgeColor','k',...
            'MarkerFaceColor',[0.4 0.8 1]...
        )
    elseif strcmp(mol.element(i),'Au') %Gold
        scatter3(mol.x(i),mol.y(i),mol.z(i),... 
            200,... 
            'Filled','MarkerEdgeColor','k',...
            'MarkerFaceColor',[1 1 0]...
        )
    elseif strcmp(mol.element(i),'DRIVER') %Driver
        scatter3(mol.x(i),mol.y(i),mol.z(i),... 
            600,... 
            'Filled','MarkerEdgeColor','k',...
            'MarkerFaceColor',[0 1 0]...
        )
    elseif strcmp(mol.element(i),'DOT1') %Driver
        scatter3(mol.x(i),mol.y(i),mol.z(i),... 
            400,... 
            'Filled','MarkerEdgeColor','k',...
            'MarkerFaceColor',[1 0 0]...
        )
    elseif strcmp(mol.element(i),'DOT2') %Driver
        scatter3(mol.x(i),mol.y(i),mol.z(i),... 
            400,... 
            'Filled','MarkerEdgeColor','k',...
            'MarkerFaceColor',[0 1 0]...
        )
    elseif strcmp(mol.element(i),'Cbz') %Driver
        scatter3(mol.x(i),mol.y(i),mol.z(i),... 
            400,... 
            'Filled','MarkerEdgeColor','k',...
            'MarkerFaceColor','y'...
        )
    elseif strcmp(mol.element(i),'Thiol') %Driver
        scatter3(mol.x(i),mol.y(i),mol.z(i),... 
            400,... 
            'Filled','MarkerEdgeColor','k',...
            'MarkerFaceColor','b'...
        )
    elseif strcmp(mol.element(i),'big') %Big
        scatter3(mol.x(i),mol.y(i),mol.z(i),... 
            200,... 
            'Filled','MarkerEdgeColor','k',...
            'MarkerFaceColor','k'...
        )
    elseif strcmp(mol.element(i),'small') %Small
        scatter3(mol.x(i),mol.y(i),mol.z(i),... 
            50,... 
            'Filled','MarkerEdgeColor','k',...
            'MarkerFaceColor','k'...
        )
    elseif strcmp(mol.element(i),'big_red') %Big
        scatter3(mol.x(i),mol.y(i),mol.z(i),... 
            200,... 
            'Filled','MarkerEdgeColor','k',...
            'MarkerFaceColor','r'...
        )
    elseif strcmp(mol.element(i),'big_blue') %Big
        scatter3(mol.x(i),mol.y(i),mol.z(i),... 
            200,... 
            'Filled','MarkerEdgeColor','k',...
            'MarkerFaceColor','b'...
        )
    elseif strcmp(mol.element(i),'small_red') %Small
        scatter3(mol.x(i),mol.y(i),mol.z(i),... 
            50,... 
            'Filled','MarkerEdgeColor','k',...
            'MarkerFaceColor','r'...
        )
    elseif strcmp(mol.element(i),'test') %Small
        scatter3(mol.x(i),mol.y(i),mol.z(i),... 
            40, ... 
            'Filled','MarkerEdgeColor','r',...
            'MarkerFaceColor','r'...
        )
    elseif strcmp(mol.element(i),'proportional') %generic
        size = max(mol.espCharge(i)*100,0.001);
        scatter3(mol.x(i),mol.y(i),mol.z(i),... 
            size, ... 
            'Filled','MarkerEdgeColor','k',...
            'MarkerFaceColor','k'...
        )
    end
end

xlabel('x [\AA]','Interpreter','Latex')
ylabel('y [\AA]','Interpreter','Latex')
zlabel('z [\AA]','Interpreter','Latex')
end

