function [ field ] = EvaluateField(driver_mol,pos)
%Evaluate the field generated by molecule in a point
%   field: is the output field
%   pos: position to evaluate the field
%       -> pos.x - pos.y - pos.z in ANGSTRONG

    %constants
    q = 1.60217662e-19;
    e0 = 8.854187817e-12;
    k = 1/(4*pi*e0);

    %number of charges
    N=driver_mol.n_atoms;

    %contribution to the field due to i-th charge is: k*qi/(|r-ri|^2)

    %evaluate field
    field = [0 0 0];
    for ii=1:N
        %evaluate distance^2
        xdist = 1e-10*(pos.x - driver_mol.x(ii));
        ydist = 1e-10*(pos.y - driver_mol.y(ii));
        zdist = 1e-10*(pos.z - driver_mol.z(ii));
        dist = sqrt(xdist.^2 + ydist.^2 + zdist.^2);

        %sum field contribution
        field = field + k*(q*driver_mol.espCharge(ii))./(dist.^3).*[xdist ydist zdist];
    end
end