function [ voltage ] = EvaluatePotential(mol,pos)
%Evaluate the voltage generated by molecule in a point
%   voltage: is the output voltage
%   pos: position to evaluate the potential
%       -> pos.x - pos.y - pos.z in ANGSTRONG

    %constants
    q = 1.60217662e-19;
    e0 = 8.854187817e-12;
    k = 1/(4*pi*e0);

    %number of charges
    N=mol.n_atoms;

    %contribution to the potential due to i-th charge is: k*qi/|r-ri|

    %evaluate voltage
    voltage = 0;
    for ii=1:N
        %evaluate distance
        xdist = 1e-10.*(pos.x - mol.x(ii));
        ydist = 1e-10.*(pos.y - mol.y(ii));
        zdist = 1e-10.*(pos.z - mol.z(ii));
        dist = sqrt(xdist.^2 + ydist.^2 + zdist.^2);

        %sumpotential contribution
        voltage = voltage + k*(q*mol.espCharge(ii))./dist;
    end
end

