#! /bin/bash 
source SERVER_ORCAINIT

sed -e "s/\r//g" MOLECULE_NAMETEMPLATE.inp

D1=($(seq CHAR_MINCHARGE CHAR_SPAN CHAR_MAXCHARGE));
D2=($(seq CHAR_MAXCHARGE -CHAR_SPAN CHAR_MINCHARGE));

CLK1=(CHAR_CLK1_SPAN);
CLK2=(CHAR_CLK2_SPAN);
CKVOLTAGE=(CHAR_VOLTAGE_SPAN);

total_drivers=${#D1[*]}
total_clocks=${#CKVOLTAGE[*]}

echo Number of drivers: $total_drivers
echo Number of clocks: $total_clocks

for i in `seq 0 $(( $total_clocks - 1 ))`;
do

    cp initialOrbitals.gbw orbitals.gbw

    for j in `seq 0 $(( $total_drivers - 1 ))`;
    do
        echo Launching simulation charges: ${D1[j]}  ${D2[j]} Clock: ${CLK1[i]}  ${CLK2[i]} \(${CKVOLTAGE[i]}\)

        # pointcharge file
        cp pointchargesTEMPLATE.pc pointcharges.pc 
        sed -i "s/PCD1/${D1[j]}/g" pointcharges.pc 
        sed -i "s/PCD2/${D2[j]}/g" pointcharges.pc 
        sed -i "s/PCLK1/${CLK1[i]}/g" pointcharges.pc 
        sed -i "s/PCLK2/${CLK2[i]}/g" pointcharges.pc 

        #name of files
        infile="MOLECULE_NAMEtc_${D1[j]}_${D2[j]}_ck${CKVOLTAGE[i]}.inp"
        gbwfile="MOLECULE_NAMEtc_${D1[j]}_${D2[j]}_ck${CKVOLTAGE[i]}.gbw"
        outfile="MOLECULE_NAMEtc_${D1[j]}_${D2[j]}_ck${CKVOLTAGE[i]}.out"

        #copy pointcharge file for debug purpose
        pcfile="MOLECULE_NAMEtc_${D1[j]}_${D2[j]}_ck${CKVOLTAGE[i]}.pc"
        cp pointcharges.pc $pcfile

        #check if simulation was already done in a previous launch
        if [[ -f "$gbwfile" ]]; then
            echo "$gbwfile already exists, skipping simulation."
        else
            #create input file
            cp MOLECULE_NAMETEMPLATE.inp $infile

            #simulation
            $ORCA_FOLDER/orca $infile > $outfile 
        fi

        #speed up calculation by copying last gbw
        cp $gbwfile orbitals.gbw
    done  

done
echo "Simulation ended! Best regards!"  | mail -s "Simulation report" USER_MAIL