#!/bin/bash
#SBATCH --job-name=JOB_NAME
#SBATCH --mail-type=ALL
#SBATCH --mail-user=USER_MAIL
#SBATCH --partition=global
#SBATCH --time=120:00:00
#SBATCH --workdir=WORKDIR
#SBATCH --output=OUT_FILENAME
#SBATCH --ntasks=NTASKS
#SBATCH --gres=gpu:0

#----------------------------
USERNAME="USER_NAME"
INFILE="INFILE_PATH"
ORCAFOLDER="ORCA_PATH"

$ORCAFOLDER/orca $INFILE